---
title: "learning.qmd"
author: "Christian A. Andersen"
format: html
editor: visual
---

## Inital setup

```{r setup}
library(tidyverse)
library(targets)

source(here::here("R/functions.R")) # soruce to the function file, where all of our favorite fun's live

tar_config_set(store = here::here("_targets")) # tell R to look in the <_targets>folder

lipidomics <- tar_read(lipidomics)
```

## results; basic stats table

```{r}
tar_read(table_descriptive_stats) |>
  knitr::kable(caption = " Title:The mean and SD of metablolites in the lipidomic dataset", )
```

## The Plot of distributions that no one saw coming

```{r}
tar_read(plot_distributions)    #d
```

## Preparing the data

```{r}

lipidomics |>
  count(code, metabolite) |>
  filter(n > 1)
# oh no, why did they mesure cholesterol 3 times?
# lets solve that issue!
```

## Compute mean of dublicated metabolites

```{r}
lipidomics |>
  dplyr::group_by(dplyr::pick(-value)) |> # what the hell does group_by do ?
  dplyr::summarise(value = base::mean(value), .groups = "keep") |>
  dplyr::ungroup()


```

```{r}
clean <- function(data) {
  data |>
    dplyr::group_by(dplyr::pick(-value)) |>
    dplyr::summarise(value = mean(value), .groups = "keep") |>
    dplyr::ungroup()
}

clean(lipidomics)
```
